[build]
  command = "npm install"
  publish = "frontend"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["better-sqlite3"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
