services:
  - type: web
    name: task3expensemanagement
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: JWT_SECRET
        generateValue: true
